In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 4, 2, 5, 3])
arr1

array([1, 4, 2, 5, 3])

In [3]:
arr2 = np.array([3.14, 4, 2, 3])
arr2

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
arr3 = np.array([1, 2, 3, 4], dtype='float32')
arr3

array([1., 2., 3., 4.], dtype=float32)

In [5]:
arr4 = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr4

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
arr5 = np.zeros(10, dtype=int)
arr5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr6 = np.ones((3, 5), dtype=float)
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
arr7 = np.full((3, 5), 3.14)
arr7

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
arr8 = np.arange(0, 20, 2)
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr9 = np.linspace(0, 1, 5)
arr9

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
arr10 = np.random.normal(0, 1, (3, 3))
arr10

array([[ 1.88357052, -0.94604242,  1.86352547],
       [-1.03527481, -0.57414738,  0.57942784],
       [-0.01226101,  0.55630524,  0.90687584]])

In [13]:
arr11 = np.random.random((3, 3))
arr11

array([[0.4190726 , 0.4074294 , 0.57992706],
       [0.32524021, 0.64923027, 0.70900213],
       [0.14805319, 0.2452382 , 0.65779485]])

In [14]:
arr12 = np.random.randint(0, 10, (3, 3))
arr12

array([[4, 0, 4],
       [0, 3, 6],
       [9, 5, 3]])

In [15]:
arr13 = np.eye(3)
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr14 = np.empty(3)
arr14

array([1., 1., 1.])

In [17]:
arr15 = np.zeros(10, dtype='int16')
arr15

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [18]:
arr16 = np.zeros(10, dtype=np.int16)
arr16

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

| 数据类型   | 描述                                                    |
| ---------- | ------------------------------------------------------- |
| bool_      | 布尔值（True或False），用一个字节存储                   |
| int_       | 默认类型（通常情况下是int64或者int32）                  |
| intc       | 同C语言的int相同                                        |
| intp       | 用作索引的整型（通常是int32或者int64）                  |
| int8       | 字节（byte，范围从-128到127）                           |
| int16      | 整型（范围从-32768到32767）                             |
| int32      | 整型（范围从-2147483648到2147483647）                   |
| int64      | 整型（范围从-9223372036854775808到9223372036854775807） |
| uint8      | 无符号整型（范围从0到255）                              |
| uint16     | 无符号整型（范围从0到65535）                            |
| uint32     | 无符号整型（范围从0到4294967295）                       |
| uint64     | 无符号整型（范围从0到18446744073709551615）             |
| float_     | float64的简化形式                                       |
| float16    | 半精度浮点型：符号比特位，5比特位指数，10比特位尾数     |
| float32    | 单精度浮点型：符号比特位，8比特位指数，23比特位尾数     |
| float64    | 双精度浮点型：符号比特位，11比特位指数，52比特位尾数    |
| comlpex_   | complex128的简化形式                                    |
| complex64  | 复数，由两个32位浮点数表示                              |
| complex128 | 复数，由两个64位浮点数表示                              |