In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 4, 2, 5, 3])
arr1

array([1, 4, 2, 5, 3])

In [3]:
arr2 = np.array([3.14, 4, 2, 3])
arr2

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
arr3 = np.array([1, 2, 3, 4], dtype='float32')
arr3

array([1., 2., 3., 4.], dtype=float32)

In [5]:
arr4 = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr4

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
arr5 = np.zeros(10, dtype=int)
arr5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr6 = np.ones((3, 5), dtype=float)
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
arr7 = np.full((3, 5), 3.14)
arr7

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
arr8 = np.arange(0, 20, 2)
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr9 = np.linspace(0, 1, 5)
arr9

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
arr10 = np.random.normal(0, 1, (3, 3))
arr10

array([[ 1.88357052, -0.94604242,  1.86352547],
       [-1.03527481, -0.57414738,  0.57942784],
       [-0.01226101,  0.55630524,  0.90687584]])

In [13]:
arr11 = np.random.random((3, 3))
arr11

array([[0.4190726 , 0.4074294 , 0.57992706],
       [0.32524021, 0.64923027, 0.70900213],
       [0.14805319, 0.2452382 , 0.65779485]])

In [14]:
arr12 = np.random.randint(0, 10, (3, 3))
arr12

array([[4, 0, 4],
       [0, 3, 6],
       [9, 5, 3]])

In [15]:
arr13 = np.eye(3)
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr14 = np.empty(3)
arr14

array([1., 1., 1.])

In [17]:
arr15 = np.zeros(10, dtype='int16')
arr15

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [18]:
arr16 = np.zeros(10, dtype=np.int16)
arr16

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)